### ISSUE TITLE
loader 沒有正確載入 header 以外的模組

### ISSUE THREAD

**Issue by jvman9527** [eHanlin/common-web-component#1]
如題，只有 header 會正確執行       

```html
 <script type="text/javascript" data-module="ehanlin-header,ehanlin-footer" src="https://s3-ap-northeast-1.amazonaws.com/ehanlin-web-resource/common_webcomponent/current/js/ehanlin-loader.js"></script>
        <header id="ehanlin-header" class="layout-top"></header>
        <footer id="ehanlin-footer" class="layout-bottom"></footer>
```

<img width="1269" alt="2017-08-04 14 38 08" src="https://user-images.githubusercontent.com/835145/28957025-98b14cc6-7922-11e7-8592-77129c30b21b.png">

**Comment by YarinSincerely** [comment]
已修正，try it~~
呼叫的 script 改為：
`https://s3-ap-northeast-1.amazonaws.com/ehanlin-web-resource/common_webcomponent/current/js/ehanlin-loader.js`

先暫時修正一版，login 登入那兒，我們會再改為原生 js

**Comment by jvman9527** [comment]
👍
