### ISSUE TITLE
loader 在 Safari 上出現錯誤 

### ISSUE THREAD

**Issue by jvman9527** [eHanlin/common-web-component#2]
<img width="1280" alt="2017-08-09 11 07 40" src="https://user-images.githubusercontent.com/835145/29103661-985ce198-7cf3-11e7-8d60-4ad7c53b46f1.png">

<img width="643" alt="2017-08-09 11 13 15" src="https://user-images.githubusercontent.com/835145/29103701-c828a498-7cf3-11e7-9bc8-e27f259effa3.png">

**Comment by YarinSincerely** [comment]
已修正：
將 createContextualFragment 改為 insertAdjacentHTML
**P.S. createContextualFragment 不支援 9.1 版以下 safari**

**Comment by jvman9527** [comment]
Awesome~
