### ISSUE TITLE
header 裡呼叫 user-status API 時使用相對路徑

### ISSUE THREAD

**Issue by jvman9527** [eHanlin/common-web-component#5]
如題，不然 header 的狀態實在對不起來。

**Comment by AsoTiesto** [comment]
路徑已修復：
[reference 1](https://github.com/eHanlin/common-web-component/commit/baad59e1ba17b597eb8a40735504c39adf329b4f)
[reference 2](https://github.com/eHanlin/common-web-component/commit/29aaa40f5f8eb47e72dfeef4d49894d074d167a4)

**Comment by jvman9527** [comment]
👍
